databases:
  - name: cloud-jeans
    plan: free

services:
  - type: web
    name: cloud-jeans
    env: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: cloud-jeans
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false